// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loaylblbkdbasbjysrxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvYXlsYmxia2RiYXNianlzcnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDQ3MDksImV4cCI6MjA1OTcyMDcwOX0.C5meNrHk8Vf2XqC3402gQ23BnV1wasKbOfhseeysLUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);